# builds and publishes ooniprobe for linux
name: ooniprobe-cli-linux
on:
  push:
    branches:
      - ooniprobe-cli-linux-staging

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        goarch:
          - "386"
          - "amd64"
          - "armv7"
          - "arm64"
    steps:
      - name: ensure we use the required version of go
        uses: actions/setup-go@v1
        with:
          go-version: "1.17.3"

      - name: update the packages index
        run: sudo apt update

      - name: upgrade packages
        run: sudo apt dist-upgrade --yes

      - name: install dependencies
        run: sudo apt-get install -y qemu-user-static

      - name: checkout github.com/bassosimone/cloud-builds
        uses: actions/checkout@v2

      - name: checkout github.com/ooni/probe-private
        uses: actions/checkout@v2
        with:
          repository: ooni/probe-private
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: probe-private

      - name: checkout github.com/ooni/probe-cli
        uses: actions/checkout@v2
        with:
          repository: ooni/probe-cli
          ref: v3.11.0-beta.1
          path: probe-cli
          fetch-depth: 0

      - name: import signing GPG key
        run: echo $GPG_KEY_BASE64 | base64 --decode | gpg --import
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}

      - name: build ooniprobe for linux/${{ matrix.goarch }}
        run: |
          cd probe-cli
          ./mk OONIPRIVATE=../probe-private GPG_USER=simone+machine@openobservatory.org ooniprobe_linux_${{ matrix.goarch }}.tar.gz.asc

      - name: show the result artifact
        run: ls ./probe-cli/ooniprobe_linux_*

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ooniprobe-cli-linux
          path: ./probe-cli/ooniprobe_linux_*
