# builds and publishes ooniprobe
name: ooniprobe-cli-macos
on:
  push:
    branches:
      - ooniprobe-cli-macos-staging

jobs:
  build_macos:
    runs-on: macos-11
    strategy:
      matrix:
        goarch:
          - "amd64"
          - "arm64"
    steps:

      - name: ensure we use the required version of go
        uses: actions/setup-go@v1
        with:
          go-version: "1.17.3"

      - name: checkout github.com/bassosimone/cloud-builds
        uses: actions/checkout@v2

      - name: checkout github.com/ooni/probe-private
        uses: actions/checkout@v2
        with:
          repository: ooni/probe-private
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: probe-private

      - name: checkout github.com/ooni/probe-cli
        uses: actions/checkout@v2
        with:
          repository: ooni/probe-cli
          ref: v3.11.0-beta.1
          path: probe-cli
          fetch-depth: 0

      - name: import signing GPG key
        run: echo $GPG_KEY_BASE64 | base64 --decode | gpg --import
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}

      - name: build ooniprobe for darwin/${{ matrix.goarch }}
        run: |
          cd probe-cli
          ./mk OONIPRIVATE=../probe-private GPG_USER=simone+machine@openobservatory.org ooniprobe_darwin_${{ matrix.goarch }}.tar.gz.asc
          file ./CLI/darwin/${{ matrix.goarch }}/ooniprobe
          shasum -a 256 ./CLI/darwin/${{ matrix.goarch }}/ooniprobe
          cp ooniprobe_darwin_${{ matrix.goarch }}.tar.gz /tmp
          cd /tmp
          tar -xzf ooniprobe_darwin_${{ matrix.goarch }}.tar.gz
          file ./ooniprobe
          shasum -a 256 ./ooniprobe

      - name: show the result artifact
        run: ls ./probe-cli/ooniprobe_darwin_*

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ooniprobe-macos
          path: ./probe-cli/ooniprobe_darwin_*
